sudo: required
services:
  - docker

before_install:
  - docker build -t sdreger/test-react -f Dockerfile.dev .

script:
  - docker run -it sdreger/test-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-572618461785"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
